# Generated by Django 3.0.6 on 2020-06-19 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 19, 58, 5, 888044, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
